version: 3
vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    # only:
    #   - "**/*.rb"
    #   - "**/LICENSE"
    exclude:
      - ./.git/**
      - "**/.gitignore"
      - "**/fossa-deps.yml"
      - "**/*.gz"
      - ./.fossa.yml
      - "**/fossa.telemetry.json"
      - "**/*_external.rb"
      - "**/src/**.rb"
